// <auto-generated />
namespace Ocean.Inside.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsHot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsHot));
        
        string IMigrationMetadata.Id
        {
            get { return "201709141123559_IsHot +"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
